# Generated by Django 4.2.16 on 2026-02-14 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wo_number', models.CharField(help_text='Auto-generated: WO-2026-0001', max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_team', models.CharField(help_text='Field crew/team name', max_length=100)),
                ('steps_text', models.TextField(help_text='Operator steps from mitigation plan')),
                ('area', models.CharField(help_text='Geographic area (substation/region)', max_length=100)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='OPEN', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('outcome_notes', models.TextField(blank=True, help_text='Field crew notes after execution')),
                ('attachments', models.FileField(blank=True, help_text='Photos, diagrams, etc.', null=True, upload_to='workorders/')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='planning.mitigationplan')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='ops_workord_status_93b1d9_idx'), models.Index(fields=['wo_number'], name='ops_workord_wo_numb_24f1df_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('FORECAST_RUN', 'Forecast Run'), ('RISK_ASSESS', 'Risk Assessment'), ('PLAN_GEN', 'Plan Generated'), ('PLAN_APPROVE', 'Plan Approved'), ('PLAN_REJECT', 'Plan Rejected'), ('WO_CREATE', 'Work Order Created'), ('WO_START', 'Work Order Started'), ('WO_COMPLETE', 'Work Order Completed'), ('WO_CANCEL', 'Work Order Cancelled'), ('DATA_UPLOAD', 'Data Upload'), ('USER_LOGIN', 'User Login'), ('USER_LOGOUT', 'User Logout'), ('CONFIG_CHANGE', 'Configuration Change')], db_index=True, max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('details_json', models.JSONField(default=dict, help_text='Structured details about the action')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('success', models.BooleanField(default=True, help_text='Whether the action completed successfully')),
                ('error_message', models.TextField(blank=True, help_text='Error details if action failed')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='ops_auditlo_timesta_6d2d47_idx'), models.Index(fields=['action_type', '-timestamp'], name='ops_auditlo_action__e7e734_idx'), models.Index(fields=['user', '-timestamp'], name='ops_auditlo_user_id_96256e_idx')],
            },
        ),
    ]
