# Generated by Django 4.2.16 on 2026-02-14 17:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_generated_at', models.DateTimeField(auto_now_add=True, help_text='When this forecast was generated')),
                ('forecast_horizon_hours', models.IntegerField(default=72, help_text='How many hours ahead this forecast predicts (default 72h)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(168)])),
                ('predictions', models.JSONField(help_text='Array of predictions: [{timestamp, predicted_kw, confidence}, ...]')),
                ('peak_predicted_kw', models.DecimalField(decimal_places=2, help_text='Maximum predicted load in the forecast period', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('peak_predicted_pct', models.DecimalField(decimal_places=2, help_text='Peak load as percentage of rated capacity', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('peak_time', models.DateTimeField(help_text='When the peak load is predicted to occur')),
                ('algorithm', models.CharField(default='baseline', help_text='Forecasting algorithm used (baseline, prophet, lstm, etc.)', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata (MAE, RMSE, parameters, etc.)')),
                ('transformer', models.ForeignKey(help_text='Transformer this forecast is for', on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='assets.transformer')),
            ],
            options={
                'verbose_name': 'Load Forecast',
                'verbose_name_plural': 'Load Forecasts',
                'ordering': ['-forecast_generated_at'],
                'indexes': [models.Index(fields=['transformer', '-forecast_generated_at'], name='forecasting_transfo_dc2ab4_idx')],
            },
        ),
    ]
