# Generated by Django 4.2.16 on 2026-02-14 16:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feeder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Feeder name (e.g., FDR-A)', max_length=100)),
                ('voltage_level', models.IntegerField(help_text='Operating voltage level in kV', validators=[django.core.validators.MinValueValidator(1)])),
                ('rated_capacity_kw', models.DecimalField(decimal_places=2, help_text='Rated capacity in kilowatts', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Feeder',
                'verbose_name_plural': 'Feeders',
                'ordering': ['substation__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Substation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Substation name (e.g., SS-01)', max_length=100, unique=True)),
                ('region', models.CharField(help_text='Geographic region', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude coordinate for mapping', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude coordinate for mapping', max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Substation',
                'verbose_name_plural': 'Substations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Switch identifier (e.g., SW-03)', max_length=100, unique=True)),
                ('switch_type', models.CharField(choices=[('NO', 'Normally Open'), ('NC', 'Normally Closed')], help_text='Normal operating state', max_length=2)),
                ('location', models.CharField(help_text='Physical location description', max_length=200)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('FAULT', 'Fault'), ('MAINTENANCE', 'Maintenance')], default='OPEN', help_text='Current operational status', max_length=20)),
                ('last_operated', models.DateTimeField(blank=True, help_text='Last time switch state was changed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feeder', models.ForeignKey(help_text='Parent feeder', on_delete=django.db.models.deletion.CASCADE, related_name='switches', to='assets.feeder')),
            ],
            options={
                'verbose_name': 'Switch',
                'verbose_name_plural': 'Switches',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transformer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Transformer name (e.g., T-01)', max_length=100, unique=True)),
                ('rated_kva', models.DecimalField(decimal_places=2, help_text='Rated capacity in kVA', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_load_pct', models.IntegerField(default=90, help_text='Safe operating limit as percentage of rated capacity', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('cooling_type', models.CharField(choices=[('ONAN', 'Oil Natural Air Natural'), ('ONAF', 'Oil Natural Air Forced'), ('OFAF', 'Oil Forced Air Forced')], help_text='Cooling system type', max_length=50)),
                ('install_year', models.IntegerField(help_text='Year of installation', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('is_active', models.BooleanField(default=True, help_text='Whether transformer is currently in service')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feeder', models.ForeignKey(help_text='Parent feeder', on_delete=django.db.models.deletion.CASCADE, related_name='transformers', to='assets.feeder')),
            ],
            options={
                'verbose_name': 'Transformer',
                'verbose_name_plural': 'Transformers',
                'ordering': ['feeder__substation__name', 'feeder__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='feeder',
            name='substation',
            field=models.ForeignKey(help_text='Parent substation', on_delete=django.db.models.deletion.CASCADE, related_name='feeders', to='assets.substation'),
        ),
        migrations.CreateModel(
            name='TopologyLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(choices=[('tie_line', 'Tie Line'), ('backup_line', 'Backup Line'), ('emergency_tie', 'Emergency Tie')], default='tie_line', help_text='Type of connection', max_length=50)),
                ('max_transfer_kw', models.DecimalField(decimal_places=2, help_text='Maximum safe power transfer in kW', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True, help_text='Whether link is available for load transfer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_transformer', models.ForeignKey(help_text='Source transformer', on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_links', to='assets.transformer')),
                ('switch', models.ForeignKey(blank=True, help_text='Switch controlling this link', null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.switch')),
                ('to_transformer', models.ForeignKey(help_text='Destination transformer', on_delete=django.db.models.deletion.CASCADE, related_name='incoming_links', to='assets.transformer')),
            ],
            options={
                'verbose_name': 'Topology Link',
                'verbose_name_plural': 'Topology Links',
                'ordering': ['from_transformer__name', 'to_transformer__name'],
                'unique_together': {('from_transformer', 'to_transformer')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='feeder',
            unique_together={('substation', 'name')},
        ),
    ]
