# Generated by Django 4.2.16 on 2026-02-14 17:35

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('risk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MitigationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('plan_json', models.JSONField(help_text='Structured transfer details: {from_transformer, to_transformer, transfer_kw, switch_id, ...}')),
                ('expected_risk_after', models.DecimalField(decimal_places=3, help_text='Predicted risk score after plan execution', max_digits=4)),
                ('expected_load_reduction_kw', models.DecimalField(decimal_places=2, help_text='Expected load reduction in kW', max_digits=10)),
                ('executive_summary', models.TextField(blank=True, help_text='Plain-language summary of the plan')),
                ('operator_steps', models.JSONField(default=list, help_text='Step-by-step instructions for control room')),
                ('field_checklist', models.JSONField(default=list, help_text='Safety checklist for field crew')),
                ('rollback_steps', models.JSONField(default=list, help_text='Emergency reversion procedures')),
                ('assumptions', models.JSONField(default=list, help_text='Key assumptions and uncertainties')),
                ('llm_confidence', models.DecimalField(decimal_places=3, default=Decimal('0.0'), help_text='LLM confidence in generated plan (0.0-1.0)', max_digits=4)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXECUTED', 'Executed')], db_index=True, default='DRAFT', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('execution_notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_plans', to=settings.AUTH_USER_MODEL)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mitigation_plans', to='risk.riskassessment')),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['status', '-generated_at'], name='planning_mi_status_79fd95_idx'), models.Index(fields=['assessment', '-generated_at'], name='planning_mi_assessm_db0826_idx')],
            },
        ),
    ]
