# Generated by Django 4.2.16 on 2026-02-14 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLMAPILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operation_type', models.CharField(default='plan_enhancement', help_text='Type of operation (e.g., plan_enhancement, explanation_generation)', max_length=50)),
                ('input_data', models.JSONField(help_text='Input sent to LLM (plan_data, etc.)')),
                ('output_data', models.JSONField(blank=True, help_text='LLM response (executive_summary, steps, etc.)', null=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('FALLBACK', 'Used Template Fallback')], max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if failed')),
                ('tokens_used', models.IntegerField(blank=True, help_text='Total tokens consumed (if available from API)', null=True)),
                ('response_time_ms', models.IntegerField(blank=True, help_text='API response time in milliseconds', null=True)),
                ('model_used', models.CharField(default='claude-sonnet-4-5-20250929', max_length=100)),
                ('related_plan_id', models.IntegerField(blank=True, help_text='MitigationPlan ID if this log is for plan enhancement', null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='llm_llmapil_created_f8a34d_idx'), models.Index(fields=['status', '-created_at'], name='llm_llmapil_status_473961_idx')],
            },
        ),
    ]
