# Generated by Django 4.2.16 on 2026-02-14 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forecasting', '0001_initial'),
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessed_at', models.DateTimeField(auto_now_add=True)),
                ('time_window_start', models.DateTimeField()),
                ('time_window_end', models.DateTimeField()),
                ('risk_score', models.DecimalField(decimal_places=3, help_text='Overall risk score: 0.000 (safe) to 1.000 (critical)', max_digits=4)),
                ('overload_pct', models.DecimalField(decimal_places=2, help_text='Predicted peak load as % of rated capacity', max_digits=5)),
                ('confidence', models.DecimalField(decimal_places=3, help_text='Confidence in this assessment (0.0-1.0)', max_digits=4)),
                ('risk_components', models.JSONField(default=dict, help_text='Breakdown of risk components: {overload: 0.x, thermal: 0.x, cascading: 0.x}')),
                ('reasons_json', models.JSONField(default=dict, help_text='Structured explanation of why this transformer is at risk')),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk (0.0-0.3)'), ('MEDIUM', 'Medium Risk (0.3-0.7)'), ('HIGH', 'High Risk (0.7-1.0)')], db_index=True, max_length=10)),
                ('forecast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessments', to='forecasting.loadforecast')),
                ('transformer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessments', to='assets.transformer')),
            ],
            options={
                'ordering': ['-risk_score', '-assessed_at'],
                'indexes': [models.Index(fields=['-risk_score', '-assessed_at'], name='risk_riskas_risk_sc_3dfaba_idx'), models.Index(fields=['transformer', '-assessed_at'], name='risk_riskas_transfo_a8906c_idx')],
            },
        ),
    ]
